### PR TITLE
 Give ways to retrieve full datums associated to datum hashes.

### LINKED ISSUE #21: Give ways to retrieve full datums associated to datum hashes
#### Describe your idea, in simple words.

Kupo should give ways for application to retrieve datum associated with specific datum hashes. This could be achieved in two ways; either:

- [ ] By storing datums found in transactions while syncing the chain; and then by providing an API entrypoint to inspect those datums.
- [ ] Or, by resolving datum hashes on-demand using the chain-sync protocol from the chain-provider. 

The trade-off between the two approaches is mainly about when the cost is paid. With the former, we pay the cost for **every transaction** of every block, since we'd now need the consumer process to also look for and store datums. This is possibly a minor cost addition though and need to be checked. 

In the latter however, the cost only occurs when requests are made to resolve a specific datum hash, and would likely be a matter of a few milliseconds per datum hash. In principle, this also sounds fine because, resolving datums would likely only happen for submitting transactions which is ultimately capped anyway by the L1 throughput. 

#### Why is it a good idea?

It seems to be a crucial but still missing pieces for making kupo a truly useful chain-index for DApps developers. Rightfully so.

#### Are you willing to work on it yourself?

Yes.

### LINKED ISSUE #44: `--prune-utxo` is not safe
#### What Git revision are you using? 
1278955a8b1c33e55c2b4d79bed374609355f5a2

#### Describe what the problem is? 
Enabling the `--prune-utxo` flag does delete results from the database the moment a spending output is discovered on chain. This is problematic because it might be that the chain has to roll back and the spending output disappears from the chain. In that case, the database is missing results that still exist on-chain.

Following situation illustrates the issue:
- addr1 has UTxO A as of block 1
- A is spent in block 3 (kupo deletes A discovering this)
- the blockchain rolls back to block 2 because blockchain things happen
- kupo does roll back to block 2 but fails to restore A as it has been created in block 1 which is never touched again

#### What should be the expected behavior?

After the rollback, kupo needs to restore those UTxOs that have not been spent due to the rollback.

#### Fixes considered

As discussed with @KtorZ the best way to go about this is to only delete results from the database when the consensus protocol guarantees that they have been spent, and that this spending operation is immutable. This ought to be the case if the block that spent a UTxO is at least `k = 2160` deep in the chain.

`--prune-utxo` is supposed to reduce memory consumption of the database. Arguably keeping spent UTxOs for at most 2160 blocks into the future should not cause trouble on most setups. For adventurous souls with tight memory constraints it may be considered to make `k` a parameter for kupo. However it is important to note that this puts the DB representation of the UTxO set at high risk of  being corrupted.

### PR DESCRIPTION
**Pull request by KtorZ**
Fixes #21 

- :round_pushpin: **Store full datum from output, in a separate table.**
    The external API remains however unchanged for now and the server will still return datum hashes from the JSON response.

- :round_pushpin: **Store datum witnessed in transactions.**
    The strategy is store all datums, and have a throttled worker which
  prune unmatched datums every minutes or so to keep the database clean.

  Note that, the `Result` type has been modified to now always carry a
  `Datum`; which can be either nothing, a hash or a full resolved datum.

  This is used interchangeably when matching results in outputs as well
  as when fetching results from the database. However, at this stage,
  fetching from the database will always yield either a hash or nothing
  (because we don't perform the joint query by default to resolve a
  datum) EVEN IF the original result had an inline datum. Conversely,
  when an original result had only a hash, if resolved, it'll instead
  carry a full resolved datum.

  This makes it convenient to manipulate results and to build an API
  around it. Note that the JSON instance still always returns datum
  hashes (when present), but will also return resolved datum when asked.

- :round_pushpin: **Add datum to Ogmios 'PartialTransaction' representation.**
  
- :round_pushpin: **Implement API logic to retrieve datums on-demand.**
    Datum are specified by hash digest and can only be retrieved one at a
  time, which should be sufficient for _most anticipated use-cases_.

  If needs be, we can also implement batch fetching of datums matching
  certain patterns or, can provide a flag to resolve when querying
  address matches.

- :round_pushpin: **Store raw binary-data hashes in database**
    Do not store them as CBOR-encoded binary strings.

  (a) It makes the database easier to explore and inspect
  (b) It's shorter (2 bytes, but still shorter) and slightly faster to do

- :round_pushpin: **Write e2e scenario waiting for a real testnet datum**
    Adding a utility function to poll the API until a certain knwon datum is seen in a transaction. Ideally, we would need slightly more complex scenarios where we can check for datums coming from witnesses and datums coming from inlined outputs. Will do eventually.

- :round_pushpin: **Fix Ogmios integration, remove compact mode.**
    We need access to the witness! Because that's where we can find the datum.

- :round_pushpin: **Update CHANGELOG with recent additions.**
  
- :round_pushpin: **Enhance configuration with longest rollback and prune throttle delay**
    As well as a few comments. In the end, having those hard-coded parameter floating around isn't good. So we better make them part of the configuration even if not actually user-configurable, they still make for application-level configuration.

- :round_pushpin: **Implement inputs & binary-data garbage collector**
    This is really killing two birds one stone. On the one hand:

  - Kupo "needs" to cleanup the database from unused binary-data. This is
    because the strategy for fetching binary-data is relatively 'dumb':
    It stores everything it sees. Though, in practice, only a fraction of
    that is relevant to end-users. Since the binary store is a
    hash-based content index, it is not a big issue to keep data around
    and carbage collect it later. What to garbage collect is defined by
    data being linked to a known input. If there's no relationship, it's
    removed.

  On the other hand, there's a bugfix:

  - Kupo has an option `--prune-utxo` to remove inputs from the database
    as they're spent. But, removing utxo _as soon as_ they are observed
    spent is risky (or more exactly, a source bug!). Indeed, data is
    only eventually immutable on the chain, and this also applies to
    data that is _consumed_. Thus, a UTxO that is spent on a certain
    fork may still exist on a different fork. Upon rollback, ite
    therefore rolls back the state of the whole database but, it doesn't
    necessarily get to re-observe inputs that it has just deleted (could
    have been created way back). And it ends up in a state where, some
    inputs that should be in the database, isn't.

  This commits tries to fix both issue in a rather simple and elegant
  way. It introduces a "garbage collector" for the database. In fact, Kupo
  already has logic to mark inputs for deletion (that's the default
  behavior when `--prune-utxo` isn't specified). That's half a garbage
  collector already! All that remains is a thread which comes and
  periodically collect results that are 'ripe' (i.e. inputs that are
  more than k blocks in the past).

  Note that, to not over-complexify things, kupo always look at the node
  tip and the database tip and consider inputs to be old enough if they
  are far enough from those tips. In practice, this is _less optimal_
  than looking at the network tip which is supposedly further in the
  future (or at minima, equal to the node's tip when fully synced).
  Thus, when the node isn't fully synced, it may keep data in the
  database for longer than necessary. This saves us from having to track
  the network tip and make things even more complex. The beauty of this
  solution is that the database can fully do pruning on its own to
  maintain its own integrity (since it already stores checkpoints, so it
  has a notion of 'tip').

  Regarding the binary data (i.e. datums), it suffices to remove datums
  that aren't associated to inputs. Since kupo only removes inputs when
  they are truly gone (and have a probability of 0 to magically
  re-appear in a fork), then the binary data are also transitively in
  sync with the tip and consistent.

  Finally, I had to remove a e2e scenario and a configuration guard
  which was ensuring that the database not contain any "spent"
  inputs if passed '--prune-utxo'. This is no longer true and while I
  could tweak / complexify the query to only count inputs mark 'spent'
  and old enough etc... Since this was mostly a UX safeguard to prevent
  people shooting themselves in the foot, it's okay-ish to remove. At
  least for now. Hopefully.

  Fixes #44

---

TODO:

- [x] Periodically remove un-matched datums from the database. 
- [ ] Additional e2e scenario highlighting an inline-datum.

### CODE REVIEW

File: src/Kupo/App/Http.hs [hunk 1]
```diff
@@ -128,6 +133,9 @@ app withDatabase patternsVar readHealth req send =
         ("v1" : "matches" : args) ->
             routeMatches (requestMethod req, args)
 
+        ("v1" : "datums" : args) ->
```
Comment (nielstron) [inline src/Kupo/App/Http.hs:136]: It might be confusing that this endpoint is called "datums" but only ever returns one datum.

Comment (KtorZ) [reply src/Kupo/App/Http.hs:136]: This is a typical convention in rest APIs. Nouns are plural just to make things consistent.

You can always read this as "get datum with hash X from the collection of datums.

Comment (KtorZ) [reply src/Kupo/App/Http.hs:136]: There's nothing worse than an API which uses both singular and plural interchangeably. So one has to pick a side and, it's usually plural because more natural in most cases

Comment (nielstron) [reply src/Kupo/App/Http.hs:136]: Wasn't aware of that convention but makes total sense :)
